### ISSUE TITLE
Adding Mod order list function

### ISSUE THREAD

**Issue by SchraderR** [SchraderR/sp-tarkov-client#143]
There is already code added → side-navigation → appcomponent → reorder
Component → src/app/components/mod-load-order/mod-load-order.component.ts

## ToDo
- [x] create initial mod order list if not available
- [x] get current mod order list of the active instance
- [x] display mod order list (cdk drag drop)
- [x] save modified mod order list
- [x] Fix Dark / Light Theme
- [x] Fix Autoscroll

**Comment by SchraderR** [comment]
## Initial Design
![grafik](https://github.com/SchraderR/sp-tarkov-client/assets/49452108/fa57a34a-6530-43a1-85f8-8444429bad2e)

- [ ] Fix Dark / Light Theme
